#!/bin/bash
# NEXTFLOW TASK: contig (test1-RGCRG-0.1)
set -e
set -u
NXF_DEBUG=${NXF_DEBUG:=0}; [[ $NXF_DEBUG > 1 ]] && set -x

nxf_env() {
    echo '============= task environment ============='
    env | sort | sed "s/\(.*\)AWS\(.*\)=\(.\{6\}\).*/\1AWS\2=\3xxxxxxxxxxxxx/"
    echo '============= task output =================='
}

nxf_kill() {
    declare -a ALL_CHILD
    while read P PP;do
        ALL_CHILD[$PP]+=" $P"
    done < <(ps -e -o pid= -o ppid=)

    walk() {
        [[ $1 != $$ ]] && kill $1 2>/dev/null || true
        for i in ${ALL_CHILD[$1]:=}; do walk $i; done
    }

    walk $1
}

nxf_mktemp() {
    local base=${1:-/tmp}
    if [[ $base == /dev/shm && ! -d $base ]]; then base=/tmp; fi 
    if [[ $(uname) = Darwin ]]; then mktemp -d $base/nxf.XXXXXXXXXX
    else TMPDIR="$base" mktemp -d -t nxf.XXXXXXXXXX
    fi
}

on_exit() {
  exit_status=${ret:=$?}
  printf $exit_status > /abi/data/puranach/packages/test_grapenf3/work/work/c1/f6ef78982f8b245754a75e26241276/.exitcode
  set +u
  [[ "$tee1" ]] && kill $tee1 2>/dev/null
  [[ "$tee2" ]] && kill $tee2 2>/dev/null
  [[ "$ctmp" ]] && rm -rf $ctmp || true
  exit $exit_status
}

on_term() {
    set +e
    [[ "$pid" ]] && nxf_kill $pid
}

trap on_exit EXIT
trap on_term TERM INT USR1 USR2

NXF_SCRATCH=''
[[ $NXF_DEBUG > 0 ]] && nxf_env
touch /abi/data/puranach/packages/test_grapenf3/work/work/c1/f6ef78982f8b245754a75e26241276/.command.begin
# task environment
export PATH="/home/puranach/envs/grape-nf3/share/nextflow/assets/guigolab/grape-nf/bin:$PATH"

[[ $NXF_SCRATCH ]] && echo "nxf-scratch-dir $HOSTNAME:$NXF_SCRATCH" && cd $NXF_SCRATCH
# stage input files
rm -f test1_m4_n10_toGenome.bam
rm -f genome.fa.fai
ln -s /abi/data/puranach/packages/test_grapenf3/work/work/a8/121b6c7c3a726ff0ee2a79a691d5be/test1_m4_n10_toGenome.bam test1_m4_n10_toGenome.bam
ln -s /abi/data/puranach/packages/test_grapenf3/work/work/06/36c5e2dcd1bc7c27b37c7af83a506a/genome.fa.fai genome.fa.fai

set +e
ctmp=$(nxf_mktemp /dev/shm)
cout=$ctmp/.command.out; mkfifo $cout
cerr=$ctmp/.command.err; mkfifo $cerr
tee .command.out < $cout &
tee1=$!
tee .command.err < $cerr >&2 &
tee2=$!
(
/bin/bash /abi/data/puranach/packages/test_grapenf3/work/work/c1/f6ef78982f8b245754a75e26241276/.command.stub
) >$cout 2>$cerr &
pid=$!
wait $pid || ret=$?
wait $tee1 $tee2
