#!/bin/bash
# NEXTFLOW TASK: mapping (test1-STAR-2.4.0j)
set -e
set -u
NXF_DEBUG=${NXF_DEBUG:=0}; [[ $NXF_DEBUG > 1 ]] && set -x

nxf_env() {
    echo '============= task environment ============='
    env | sort | sed "s/\(.*\)AWS\(.*\)=\(.\{6\}\).*/\1AWS\2=\3xxxxxxxxxxxxx/"
    echo '============= task output =================='
}

nxf_kill() {
    declare -a ALL_CHILD
    while read P PP;do
        ALL_CHILD[$PP]+=" $P"
    done < <(ps -e -o pid= -o ppid=)

    walk() {
        [[ $1 != $$ ]] && kill $1 2>/dev/null || true
        for i in ${ALL_CHILD[$1]:=}; do walk $i; done
    }

    walk $1
}

nxf_mktemp() {
    local base=${1:-/tmp}
    if [[ $base == /dev/shm && ! -d $base ]]; then base=/tmp; fi 
    if [[ $(uname) = Darwin ]]; then mktemp -d $base/nxf.XXXXXXXXXX
    else TMPDIR="$base" mktemp -d -t nxf.XXXXXXXXXX
    fi
}

on_exit() {
  exit_status=${ret:=$?}
  printf $exit_status > /abi/data/puranach/packages/test_grapenf3/work/cf/96026e7bf65c94dadb4960c2fe4989/.exitcode
  set +u
  [[ "$tee1" ]] && kill $tee1 2>/dev/null
  [[ "$tee2" ]] && kill $tee2 2>/dev/null
  [[ "$ctmp" ]] && rm -rf $ctmp || true
  exit $exit_status
}

on_term() {
    set +e
    [[ "$pid" ]] && nxf_kill $pid
}

trap on_exit EXIT
trap on_term TERM INT USR1 USR2

NXF_SCRATCH=''
[[ $NXF_DEBUG > 0 ]] && nxf_env
touch /abi/data/puranach/packages/test_grapenf3/work/cf/96026e7bf65c94dadb4960c2fe4989/.command.begin
# task environment
export PATH="/home/puranach/envs/grape-nf3/share/nextflow/assets/guigolab/grape-nf/bin:$PATH"

[[ $NXF_SCRATCH ]] && echo "nxf-scratch-dir $HOSTNAME:$NXF_SCRATCH" && cd $NXF_SCRATCH
# stage input files
rm -f test1_1.fastq.gz
rm -f test1_2.fastq.gz
rm -f annotation.gtf
rm -f genomeDir
ln -s /home/puranach/envs/grape-nf3/share/nextflow/assets/guigolab/grape-nf/data/test1_1.fastq.gz test1_1.fastq.gz
ln -s /home/puranach/envs/grape-nf3/share/nextflow/assets/guigolab/grape-nf/data/test1_2.fastq.gz test1_2.fastq.gz
ln -s /home/puranach/envs/grape-nf3/share/nextflow/assets/guigolab/grape-nf/data/annotation.gtf annotation.gtf
ln -s /abi/data/puranach/packages/test_grapenf3/work/a7/41f5068b04158e63e565c96c2aeafe/genomeDir genomeDir

set +e
ctmp=$(nxf_mktemp /dev/shm)
cout=$ctmp/.command.out; mkfifo $cout
cerr=$ctmp/.command.err; mkfifo $cerr
tee .command.out < $cout &
tee1=$!
tee .command.err < $cerr >&2 &
tee2=$!
(
/bin/bash /abi/data/puranach/packages/test_grapenf3/work/cf/96026e7bf65c94dadb4960c2fe4989/.command.stub
) >$cout 2>$cerr &
pid=$!
wait $pid || ret=$?
wait $tee1 $tee2
